### ISSUE TITLE
Object counter for maps

### ISSUE THREAD

**Issue by freghar** [CntoDev/Useful-Scripts#3]
I got this idea when fixing `housedestructionsmoke`, feel free to take and work on this.

Create a script that would take `worldName` and `worldSize` and split the map into 100x100 meter squares, creating a `CBA_fnc_hash*` or vanilla `hashCreateMap` (devbranch currently) for each square. Then go through all `nearestTerrainObjects [player, [], 1000000, false, true]` objects and, based on their X and Y `position`, assign them to the given hashes.

Then draw solid red squares on the map, one for each 100x100m square, covering it, and set the alpha value according to how many objects are in the hash of that specific square, so that less objects = more transparency. Finally, add some text-based marker to the middle of the square with a number showing the object count. ... Use average count of objects per 100x100m of Altis for the 100% transparent state, and a square with the most objects on Tanoa for the 0% transparent state, so that we can compare maps in absolute "red-ness" terms.

Also add (somewhere to the side) text-based marker with total objects overall.

The intention behind all this is to help estimate the FPS impact of maps and their specific areas, since it's fairly hard to measure FPS directly due to object occluders. It should be pretty accurate since the geometry of an object doesn't matter as much as their count.

**Comment by freghar** [comment]
Actually, there's no need for a hashmap, just use a 3D array, 2 dimensions for 100x100 square index, the 3rd dimension for a list of objects (`pushBack`) in that square.

It would also be great if `nearestTerrainObjects` would be in a separate function providing a list of objects - that way, a user could use a custom function that counts mission-placed / simpleobjects in addition to terrain objects. You don't really need to care, `position` works on any type of object.

**Comment by Seb105** [comment]
Perhaps each 100m square should count every object within 1km rather than its own area, as that is about the standard render distance for infantry

EDIT: Or have that customisable, as you can actually force ACE render distance via mission this would almost provide a "recommended render distance"

**Comment by Seb105** [comment]
https://github.com/CntoDev/Useful-Scripts/blob/master/fnc_perfProfileMap.sqf
![107410_20210122150415_1](https://user-images.githubusercontent.com/65898127/105510275-5b4d3a80-5cc6-11eb-80f9-9d1085790225.png)

![107410_20210122151226_1](https://user-images.githubusercontent.com/65898127/105510276-5c7e6780-5cc6-11eb-9e1d-b6e20fdbf17c.png)
![107410_20210122150802_1](https://user-images.githubusercontent.com/65898127/105510280-5d16fe00-5cc6-11eb-8251-4e62a1fbc426.png)
![107410_20210122150614_1](https://user-images.githubusercontent.com/65898127/105510282-5daf9480-5cc6-11eb-8568-78e9b4cd9d82.png)

**Comment by freghar** [comment]
So, I gave this a shot as well, but measuring real FPS instead. I originally used `BIS_fnc_arithmeticMean` of `diag_fps` over 10 seconds, but it turns out `diag_fps` itself is pretty consistent on an empty static map, so I dropped any further averaging.

![20210130161649_1](https://user-images.githubusercontent.com/23681/106360683-bfe54680-6311-11eb-82db-88cb6c9c5c3d.jpg)
The first image is with 2000m view distance, with `linearConversion` between max FPS value and 0 as the worst case. Pretty average overall.

![20210130163354_1](https://user-images.githubusercontent.com/23681/106360703-eefbb800-6311-11eb-929e-24576419cf6a.jpg)
The second one is 1000m view distance, so it a tiny bit clearer.

![20210130163432_1](https://user-images.githubusercontent.com/23681/106360729-13f02b00-6312-11eb-8110-4dbd088a76f7.jpg)
Third image shows changing `linearConversion` from overall average FPS down to 0, in hopes of getting more visible resolution out of that avg-to-min range. Didn't work quite as I expected.

![20210130163518_1](https://user-images.githubusercontent.com/23681/106360763-4e59c800-6312-11eb-85cb-d4509f9f3af4.jpg)
Lastly, this is the 1000m example, but with FPS numbers.

The numbers really tell the story of what's wrong - naively measuring from the top has its issues, namely that it's not representative of what the player would experience. I could go super high with the camera, but then LODs become low resolution and FPS go unrealistically high up. Too low and you have the same problem.

In my code, I tried to combat some false positives where the camera got teleported inside a building and had super high FPS (due to [object occluders](https://community.bistudio.com/wiki/Geometric_Occluders) blocking view to outside) - that's the invisible helipad hack, to calculate the highest surface (not just terrain) and go `_height` above that surface, but still low enough to get high resolution LODs.

The first 2 runs are to cache the high-res LODs in memory - it takes a surprising amount of time (30+ seconds) because Arma still throttles loading as if it was reading a HDD, especially when you try to load too much at once.
The code also sleeps 2 seconds between shots by default, this is because it takes 1-1.5sec to switch the LOD and stabilize the scene, and the hope is that the remaining 0.5sec is enough for the 16 frames of `diag_fps`.

In the end, this is a flawed approach and a better one would be needed - ie. choosing 16 angles for each grid position, aiming the camera at 45deg angle down from ~50m up and doing a circular sweep, averaging the FPS.
Or something even more advanced - looking directly ahead, but accounting the FPS to grids in that direction, not to the current grid. This would tax forests and urban areas without occluders way more accurately.

I wish I had time for all this nonsense.

```sqf
measure_map_fps = {
    params ["_gridsize", ["_preload",2], ["_height",20]];

    private _cam = "camera" camCreate [0,0,0];
    _cam camSetDir [0,0,-1];
    _cam camCommit 0;
    switchCamera _cam;

    private _fpsdata = [];
    private _start = _gridsize / 2;
    private _end = worldSize - _start;
    private _total = (floor (worldSize / _gridsize))^2;
    private _i = 1;
    for "_posX" from _start to _end step _gridsize do {
        for "_posY" from _start to _end step _gridsize do {
            private _obj = createVehicle [
                "Land_HelipadEmpty_F", [_posX, _posY, 10000], [], 0, "CAN_COLLIDE"
            ];
            _obj setVehiclePosition [ASLToAGL getPosASL _obj, [], 0, "CAN_COLLIDE"];
            private _camZ = (getPosASL _obj)#2 + _height;
            deleteVehicle _obj;
            _cam setPosASL [_posX, _posY, _camZ];
            sleep _preload;
            _fpsdata pushBack [[_posX, _posY], parseNumber (diag_fps toFixed 0)];
            systemChat format ["%1 / %2", _i, _total];
            _i = _i + 1;
        };
    };

    camDestroy _cam;
    switchCamera player;
    [_gridsize, _fpsdata];
};

draw_map_fps = {
    params ["_fpsdata", "_avg", "_max", ["_numbers", false]];
    _fpsdata params ["_gridsize", "_fpsdata"];

    private _fps_only = _fpsdata apply { _x#1 };
    if (isNil "_avg") then {
        _avg = _fps_only call BIS_fnc_arithmeticMean;
    };
    if (isNil "_max") then {
        _max = selectMax _fps_only;
    };

    { deleteMarker _x } forEach allMapMarkers;
    {
        _x params ["_pos", "_fps"];
        private _alpha  = linearConversion [_avg, _max, _fps, 1, 0, true];
        private _area = createMarker [format ["area_%1", _pos], _pos];
		_area setMarkerShape "RECTANGLE";
		_area setMarkerColor "ColorRed";
		_area setMarkerSize [_gridsize / 2, _gridsize / 2];
		_area setMarkerAlpha _alpha;	
        if (_numbers) then {
            private _number = createMarker [format ["number_%1", _pos], _pos];
            _number setMarkerType "mil_dot";
            _number setMarkerSize [0, 0];
            _number setMarkerText (_fps toFixed 0);
        };
    } forEach _fpsdata;
};

[] spawn {
    [500, 0.05] call measure_map_fps;
    sleep 30;
    [500, 0.05] call measure_map_fps;
    sleep 30;
    private _fpsdata = [500] call measure_map_fps;
    copyToClipboard str _fpsdata;
};

private _fpsdata = parseSimpleArray copyFromClipboard;
[_fpsdata] call draw_map_fps;
//[_fpsdata, nil, nil, true] call draw_map_fps;
```

**Comment by freghar** [comment]
I think we can close this - the object counting function was included in the repo and there's no obvious solution to the direct FPS counting.
